name: CI - CodeceptJS Playwright

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-codeceptjs --save-dev

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas
        run: npm run features

      - name: Generar reporte Allure
        run: |
          npm install -g allure-commandline --save-dev
          allure generate output --clean -o allure-report

      - name: Subir artefacto del reporte
        uses: actions/upload-artifact@v4
        with:
          name: reporte-allure
          path: output/allure-report
       
      - name: Desplegar reporte en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/allure-report
          publish_branch: main

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generar reporte de Allure
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_history: gh-pages
          allure_report: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
